### ISSUE TITLE
Error while installing node v12.2.0, npm 6.9.0

### ISSUE THREAD

**Issue by Lakkanna** [implausible/find-git-repositories#4]
![Screen Shot 2019-07-11 at 11 49 15 AM](https://user-images.githubusercontent.com/32791713/61026850-33430280-a3d2-11e9-9611-e1e57b5be9d2.png)

**Comment by Lakkanna** [comment]
It was node version problem, I used node version 10.16.0 it's working fine.

**Comment by manukashyap** [comment]
![image](https://user-images.githubusercontent.com/6327999/62879276-687f9f00-bd48-11e9-980a-00664dd92ca0.png)
Error message : ../src/FindGitRepos.cpp:155:58: error: too few arguments to function call, single argument 'context' was not specified
    New<v8::FunctionTemplate>(FindGitRepos)->GetFunction()

Sorry, but I still getting this error message, with your specified node version. Could you let me know of the other changes you tried?

**Comment by kittaakos** [comment]
> Sorry, but I still getting this error message, with your specified node version. Could you let me know of the other changes you tried?

@manukashyap, see #5.

**Comment by implausible** [comment]
This is fixed in v0.1.2
